### PR TITLE
Bump observability apps

### PR DESCRIPTION
**Pull request by QuentinBisson**
### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade
/run cluster-test-suites

### CODE REVIEW

**Review by calvix — APPROVED** [review]

**Comment by QuentinBisson** [comment]
@calvix FYI I also changed the app-operator adepends on annotation to rely on clusterName instead of clusterID because this causes `helm template` to fail

**Comment by calvix** [comment]
> @calvix FYI I also changed the app-operator adepends on annotation to rely on clusterName instead of clusterID because this causes `helm template` to fail

I wonder if we should rather rely on `{{ include "name" . }}` as that is used in the chart as the name 

TBH I copied this from cluster-aws so not sure why we used clusterID in the first place

**Comment by QuentinBisson** [comment]
I think we use clusterID because this was taken from vintage and the vintate cluster operator configures clusterID and not clusterName :)

**Comment by QuentinBisson** [comment]
Regarding the clusterID, it is still used by the observability bundle but the value comes from the cluster-apps-operator so we can probably ditch it from here :)

**Pull request merged**
